In [5]:
fx<-function(n,B0,B1,B2,mx1,mx2,sdx2,me,sde){
    for(i in 1:1000){
        x1[i]<-rt(n,mx1)
        x2[i]<-runif(n,mx2,sdx2)
        e[i]<-runif(n,me,sde)
        Y[i]<-B0+(B1*x1)+(B2*x2)+e
        model<-lm(Y~x1+x2)
    }
    return(Y)
}


In [6]:
error <- rnorm(100, 0,1)
x1 <- rt(100,4)
x2 <- runif(100,130,200)

In [8]:
error <- rnorm(100, 0,1)
x1 <- rt(100,4)
x2 <- runif(100,130,200)
Y <- 4 + 2.5*x1 + 1.87*x2 + error
Y

[1] 246.9697 294.8392 335.7076 344.4296 319.1257 344.3336 286.2928 328.4633
  [9] 333.4044 364.7411 318.8036 282.0767 289.0845 266.9917 294.2461 304.6806
 [17] 324.1142 328.9183 369.5805 331.8152 296.6947 354.3176 345.1701 288.8572
 [25] 283.1945 380.4488 253.6465 334.4984 283.3857 260.6685 368.3998 333.6739
 [33] 265.4842 285.5151 350.9893 268.0764 353.0752 355.9512 272.1338 338.5322
 [41] 370.6434 364.1351 328.6455 300.6030 269.7425 356.3410 373.3665 249.3639
 [49] 340.0791 255.4382 283.7553 347.3707 365.4757 312.7635 322.8935 302.9328
 [57] 310.9374 354.9583 280.6661 313.5138 277.3221 313.2176 305.6086 325.3606
 [65] 360.8958 285.9504 360.6406 377.6703 340.8173 312.0836 322.1958 302.8820
 [73] 293.0387 318.0782 256.1161 258.1234 316.7083 330.4524 304.0388 323.7236
 [81] 374.7138 350.2480 330.1373 272.2612 287.0340 283.4836 300.5915 369.6847
 [89] 328.9222 291.2253 367.9120 268.4273 336.4116 322.5673 324.6055 297.3437
 [97] 315.3297 310.9201 267.7830 313.8507

In [9]:
Model <- lm(Y ~ x1 + x2)
summary(Model)


Call:
lm(formula = Y ~ x1 + x2)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.35134 -0.57286 -0.04974  0.62999  2.48395 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 1.939977   0.834262   2.325   0.0221 *  
x1          2.493972   0.059675  41.792   <2e-16 ***
x2          1.882650   0.004968 378.990   <2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9077 on 97 degrees of freedom
Multiple R-squared:  0.9993,	Adjusted R-squared:  0.9993 
F-statistic: 7.305e+04 on 2 and 97 DF,  p-value: < 2.2e-16


In [10]:
betanote <- 4.0
betaone <- 2.5
betatwo <- 1.87
sims <- 1000
model.data <- data.frame(matrix(ncol = 3, nrow = sims))
colnames(model.data) <- c("Beta0", "Beta1", "Beta2")
for(i in 1:sims){
ertm <- rnorm(100, 0,1)
X1 <- rt(100, 4)
X2 <- runif(100,130,200)
Y <- betanote + betaone*X1 + betatwo*X2 + ertm
model.data[i,] <- data.frame(t(lm(Y ~X1 + X2)$coeff))
}
model.data

Beta0    Beta1    Beta2   
1    3.781850 2.574710 1.871085
2    2.811053 2.588156 1.875653
3    2.743500 2.446956 1.877837
4    4.078950 2.611623 1.869937
5    2.553844 2.414399 1.878507
6    4.007612 2.439624 1.869766
7    4.833441 2.603461 1.864622
8    4.162631 2.664570 1.869015
9    4.149834 2.542297 1.869639
10   3.654914 2.490946 1.871558
11   3.966068 2.488269 1.868702
12   3.776400 2.437797 1.872190
13   3.525024 2.494316 1.874119
14   2.429012 2.442901 1.878473
15   2.615908 2.524086 1.877959
16   3.096859 2.463496 1.875273
17   3.260158 2.561397 1.875138
18   3.990749 2.407089 1.871086
19   4.273722 2.491432 1.868448
20   4.344054 2.544170 1.866773
21   4.549646 2.456670 1.866269
22   4.299382 2.485814 1.868129
23   4.277056 2.529410 1.869205
24   4.371741 2.437569 1.867376
25   2.371012 2.483099 1.879393
26   4.106763 2.534044 1.869337
27   2.900447 2.484199 1.877376
28   4.790218 2.557911 1.865473
29   4.927926 2.579270 1.863999
30   4.692831 2.395761 1.865853
⋮    ⋮        ⋮        ⋮       
971  5.140124 2.557809 1.862195
972  4.421973 2.535946 1.867254
973  4.834837 2.522610 1.865482
974  3.251620 2.447560 1.874240
975  4.436183 2.441506 1.866849
976  3.481481 2.459802 1.873059
977  6.829192 2.577348 1.853612
978  3.684242 2.516149 1.872037
979  4.222558 2.513280 1.869039
980  4.759923 2.447836 1.865151
981  3.977898 2.511980 1.869563
982  4.923916 2.442934 1.863818
983  4.953857 2.505040 1.865643
984  3.915251 2.479897 1.870127
985  4.452896 2.480521 1.866917
986  3.046486 2.469933 1.876979
987  3.308419 2.439958 1.872870
988  3.454763 2.369435 1.872374
989  4.491737 2.486978 1.867860
990  3.632703 2.497920 1.872166
991  3.784651 2.620326 1.872662
992  3.919571 2.651617 1.871906
993  3.606079 2.432251 1.872311
994  4.174885 2.431101 1.869264
995  3.458734 2.584578 1.872696
996  3.432508 2.410141 1.873954
997  3.458216 2.416535 1.873570
998  2.888987 2.458166 1.876341
999  4.451607 2.392563 1.867313
1000 5.365557 2.604692 1.860496

In [14]:
betanote <- 150
betaone <- 4
sims <- 1000
coeff_matrix <- matrix(NA, nrow = sims, ncol = 2)

for (i in 1:sims) {
  error <- rnorm(100, 0, 1)
  X <- rnorm(100, 50,9)
  Y <- betanote + betaone * X + error
  lm_model <- lm(Y ~ X1)
  coeff_matrix[i, ] <- coef(lm_model)
}

coeff_matrix


[,1]     [,2]       
 [1,] 345.5416  3.17020542
 [2,] 355.9827  4.95435424
 [3,] 350.8384 -2.17301746
 [4,] 355.1548 -0.06324266
 [5,] 350.9734 -4.75745094
 [6,] 348.4084  0.58120376
 [7,] 343.6090  1.68522620
 [8,] 350.3770 -0.64357511
 [9,] 354.8563 -1.32911638
[10,] 354.2267 -4.34091494
[11,] 348.0836 -1.39880881
[12,] 344.2002 -0.51137311
[13,] 353.1355 -0.05823298
[14,] 350.9856  1.37229859
[15,] 350.4131 -2.17079386
[16,] 351.1797  1.39448803
[17,] 354.9926  3.32979813
[18,] 345.4557  0.65319655
[19,] 344.7811  7.46141167
[20,] 355.2691 -0.94957159
[21,] 349.3801  4.53377064
[22,] 348.8325  0.68802874
[23,] 354.9975  0.78403644
[24,] 353.3197  5.50954934
[25,] 350.3778  0.03848770
[26,] 347.1644 -1.71407986
[27,] 347.6054  1.97163262
[28,] 352.0725 -4.85748551
[29,] 348.8825  0.96709837
[30,] 346.1913  0.13455518
[31,] ⋮        ⋮          
[32,] 351.3787 -0.1280422 
[33,] 348.4461 -0.3466506 
[34,] 356.4157 -1.3183697 
[35,] 347.0029  2.2521023 
[36,] 351.7219  6.1092846 
[37,] 354.7650  0.3438599 
[38,] 349.9686  0.1180087 
[39,] 351.7309 -4.8193500 
[40,] 351.1357 -1.3074451 
[41,] 347.6311 -3.8419395 
[42,] 347.0958  1.4390411 
[43,] 344.7412  2.7463521 
[44,] 352.1618 -1.6887106 
[45,] 349.6875 -2.7570063 
[46,] 344.7513 -2.9053788 
[47,] 345.1274  0.4369366 
[48,] 347.8502 -0.6988775 
[49,] 353.4652 -1.2387623 
[50,] 351.0247  0.1654302 
[51,] 355.0807 -1.5861594 
[52,] 350.9347 -0.7077645 
[53,] 356.9133  0.5135720 
[54,] 353.2710 -0.2238765 
[55,] 348.6993  4.5932123 
[56,] 354.2687  1.0189080 
[57,] 353.5051  3.0555548 
[58,] 355.5591  0.9980406 
[59,] 345.7296  2.2483123 
[60,] 345.3056 -1.4254252 
[61,] 347.3377 -4.4129267

In [19]:
simulate_linear_regression <- function(betanote, betaone, sims) {
  coeff_matrix <- matrix(NA, nrow = sims, ncol = 2)

  for (i in 1:sims) {
    error <- rnorm(100, 0, 1)
    X <- rnorm(100, 50, 9)
    Y <- betanote + betaone * X + error
    lm_model <- lm(Y ~ X)
    coeff_matrix[i, ] <- coef(lm_model)
  }
  
  return(coeff_matrix)  

}

result <- simulate_linear_regression(150, 4, 1000)
print(result)


            [,1]     [,2]
   [1,] 149.2284 4.017100
   [2,] 150.5639 3.992559
   [3,] 149.4694 4.009929
   [4,] 150.2457 3.997384
   [5,] 150.2510 3.993068
   [6,] 150.1946 3.993410
   [7,] 150.2093 3.995196
   [8,] 149.5398 4.011503
   [9,] 149.5496 4.008766
  [10,] 149.1774 4.020733
  [11,] 149.7590 4.004374
  [12,] 150.3278 3.992472
  [13,] 149.9482 4.001206
  [14,] 150.9839 3.981613
  [15,] 151.4196 3.969435
  [16,] 149.7096 4.010189
  [17,] 150.3999 3.990533
  [18,] 150.1533 3.993985
  [19,] 149.5118 4.011632
  [20,] 149.7177 4.008696
  [21,] 150.4015 3.991703
  [22,] 149.7260 4.003891
  [23,] 150.3008 3.990817
  [24,] 149.4757 4.008033
  [25,] 149.9203 4.001660
  [26,] 150.8168 3.983107
  [27,] 149.3123 4.013777
  [28,] 149.1159 4.019563
  [29,] 149.7866 4.005954
  [30,] 148.5494 4.026672
  [31,] 150.3455 3.993846
  [32,] 149.7579 4.008148
  [33,] 150.6899 3.987757
  [34,] 150.3788 3.994570
  [35,] 150.0155 4.000012
  [36,] 151.5386 3.971182
  [37,] 149.5818 4.009697
  [38,] 150.

In [17]:
simulate_linear_regression <- function(betanote, betaone, sims) {
  coeff_matrix <- matrix(NA, nrow = sims, ncol = 2)

  for (i in 1:sims) {
    error <- rnorm(100, 0, 1)
    X <- rnorm(100, 50, 9)
    Y <- betanote + betaone * X + error
    lm_model <- lm(Y ~ X)
    coeff_matrix[i, ] <- coef(lm_model)
  }

  return(coeff_matrix)
}


betanote <- 150
betaone <- 4
sims <- 1000

result <- simulate_linear_regression(betanote, betaone, sims)
print(result)


            [,1]     [,2]
   [1,] 149.0700 4.020988
   [2,] 150.1711 3.995970
   [3,] 149.7316 4.003674
   [4,] 149.7989 4.006938
   [5,] 149.8535 4.004836
   [6,] 149.7584 4.003087
   [7,] 149.8488 4.000875
   [8,] 149.6816 4.006997
   [9,] 150.1850 3.996264
  [10,] 150.2720 3.992925
  [11,] 150.4513 3.988287
  [12,] 149.5467 4.009398
  [13,] 150.2526 3.994698
  [14,] 150.9068 3.984109
  [15,] 150.1142 3.998326
  [16,] 150.0210 4.002280
  [17,] 150.1887 4.000971
  [18,] 150.5329 3.989142
  [19,] 150.4894 3.988225
  [20,] 149.7729 4.004395
  [21,] 150.2197 3.994645
  [22,] 149.4065 4.011245
  [23,] 150.1971 3.998572
  [24,] 149.6544 4.004840
  [25,] 150.2371 3.992436
  [26,] 149.2217 4.014805
  [27,] 149.9522 4.002274
  [28,] 150.3053 3.994254
  [29,] 149.1820 4.016644
  [30,] 148.8538 4.017286
  [31,] 149.6366 4.008255
  [32,] 149.8984 4.002438
  [33,] 149.5920 4.012175
  [34,] 149.9598 4.002758
  [35,] 151.3141 3.973618
  [36,] 150.3952 3.990778
  [37,] 149.6204 4.008248
  [38,] 148.

In [21]:
simulate_linearsim<- function(n,betanote, betaone, sims,mx,sdx,me,sde) {
  coeff_matrix <- matrix(NA, nrow = sims, ncol = 2)

  for (i in 1:sims) {
    error <- rnorm(n, me, sde)
    X <- rnorm(n, mx, sdx)
    Y <- betanote + betaone * X + error
    lm_model <- lm(Y ~ X)
    coeff_matrix[i, ] <- coef(lm_model)
  }
  
  return(coeff_matrix)  

}

result <- simulate_linearsim(100,150, 4, 1000,50,9,0,100)
print(result)


              [,1]      [,2]
   [1,]  23.777205 6.3847658
   [2,] 172.439634 3.2517135
   [3,] 270.010342 1.5668148
   [4,]  92.191012 5.3417891
   [5,] 204.124082 2.8307484
   [6,] 239.353111 2.5946224
   [7,] 266.018287 1.6131867
   [8,]  60.138522 5.9357377
   [9,] 164.324554 3.7671730
  [10,]  61.780049 5.4526282
  [11,] 139.940778 4.4632765
  [12,]  84.465900 5.1741814
  [13,] 173.400109 3.3998257
  [14,] 199.341728 3.0547146
  [15,] 211.477877 2.6019281
  [16,]  82.009949 5.2105993
  [17,] 154.792884 4.2132626
  [18,] 184.828270 3.4941814
  [19,] 256.598606 1.9140150
  [20,] 108.872046 4.5077111
  [21,] 167.960392 3.8219326
  [22,] 112.714300 4.5875719
  [23,] 164.726893 3.7788575
  [24,] 151.487782 3.6869864
  [25,] 221.026419 2.5870225
  [26,] 137.447195 4.2293122
  [27,] 184.261818 3.4943158
  [28,] 127.719741 4.6958958
  [29,] 175.792412 3.8993801
  [30,] 249.970087 2.2698837
  [31,]  99.965761 5.0981831
  [32,] 258.894077 1.9014815
  [33,]  97.794478 5.2048152
  [34,] 208.01

In [22]:
calculate_bias_variance_mse <- function(coeff_matrix, betanote, betaone) {
  n_sims <- nrow(coeff_matrix)
  
  # Initialize variables to store the bias, variance, and MSE
  bias <- numeric(2)
  variance <- numeric(2)
  mse <- numeric(2)
  
  for (j in 1:2) {
    # Calculate the bias
    bias[j] <- mean(coeff_matrix[, j]) - (ifelse(j == 1, betanote, betaone))
    
    # Calculate the variance
    variance[j] <- var(coeff_matrix[, j])
    
    # Calculate the mean squared error
    mse[j] <- bias[j]^2 + variance[j]
  }
  
  result <- data.frame(Bias = bias, Variance = variance, MSE = mse)
  return(result)
}

# Example usage
coeff_matrix <- simulate_linearsim(100, 150, 4, 1000, 50, 9, 0, 100)
result_summary <- calculate_bias_variance_mse(coeff_matrix, 150, 4)
print(result_summary)


         Bias    Variance         MSE
1 0.010800010 3276.206742 3276.206859
2 0.003878483    1.289354    1.289369


In [23]:
calculate_bias_variance_mse <- function(coeff_matrix, betanote, betaone) {
  n_sims <- nrow(coeff_matrix)
  
  bias <- numeric(2)
  variance <- numeric(2)
  mse <- numeric(2)
  
  for (j in 1:2) {
    bias[j] <- mean(coeff_matrix[, j]) - (ifelse(j == 1, betanote, betaone))
    
    variance[j] <- var(coeff_matrix[, j])
    
    mse[j] <- bias[j]^2 + variance[j]
  }
  
  result <- data.frame(Bias = bias, Variance = variance, MSE = mse)
  return(result)
}

coeff_matrix <- simulate_linearsim(100, 150, 4, 1000, 50, 9, 0, 100)
result_summary <- calculate_bias_variance_mse(coeff_matrix, 150, 4)
print(result_summary)


         Bias    Variance        MSE
1 -2.90787206 3428.757759 3437.21348
2  0.05212388    1.326353    1.32907


In [ ]:
betanote <- 150
betaone <- 4
sims <- 1000
coeff_matrix <- matrix(NA, nrow = sims, ncol = 2)

for (i in 1:sims) {
  error <- rnorm(100, 0, 1)
  X <- rnorm(100, 50,9)
  Y <- betanote + betaone * X + error
  lm_model <- lm(Y ~ X1)
  coeff_matrix[i, ] <- coef(lm_model)
}

coeff_matrix


In [27]:
model_data <- function(betanote, betaone, betatwo, error, sims) {
  model.data <- data.frame(matrix(ncol = 3, nrow = sims))
  colnames(model.data) <- c("Beta0", "Beta1", "Beta2")
  
  for (i in 1:sims) {
    ertm <- rnorm(100, 0, 1)
    X1 <- rt(100, 4)
    X2 <- runif(100, 130, 200)
    Y <- betanote + betaone * X1 + betatwo * X2 + ertm
    model.data[i, ] <- data.frame(t(lm(Y ~ X1 + X2)$coeff))
  }
  
  return(model.data)
}
betanote <- 4.0
betaone <- 2.5
betatwo <- 1.87
error <- 1
sims <- 1000

result_data <- model_data(betanote, betaone, betatwo, error, sims)
result_data

Beta0    Beta1    Beta2   
1    4.575698 2.478384 1.865843
2    4.271315 2.500594 1.868378
3    4.188172 2.565514 1.869386
4    4.647778 2.446259 1.865582
5    4.448626 2.582622 1.866453
6    4.577140 2.353783 1.865976
7    4.399348 2.428444 1.867877
8    3.991658 2.652500 1.870803
9    4.271592 2.504969 1.867487
10   2.496925 2.541850 1.879685
11   4.629845 2.559642 1.866738
12   3.019821 2.476394 1.875249
13   4.027722 2.511244 1.869698
14   1.779759 2.643719 1.884081
15   3.577573 2.344941 1.873364
16   4.502532 2.468200 1.865907
17   3.889402 2.498740 1.869431
18   4.603411 2.553681 1.866573
19   3.043508 2.625620 1.874233
20   4.018205 2.470676 1.870435
21   3.919720 2.424201 1.870614
22   3.533004 2.450378 1.873134
23   3.550273 2.508575 1.872617
24   4.360032 2.476724 1.867744
25   3.216652 2.533842 1.874558
26   2.411159 2.496762 1.878389
27   3.055144 2.454447 1.876134
28   5.504057 2.478048 1.861005
29   3.574230 2.483136 1.873158
30   3.595287 2.695489 1.872507
⋮    ⋮        ⋮        ⋮       
971  4.299632 2.507530 1.867814
972  3.742321 2.556456 1.870752
973  4.502395 2.483147 1.866894
974  3.178829 2.661092 1.874477
975  4.658913 2.432873 1.866289
976  4.017194 2.534900 1.870450
977  3.774181 2.524498 1.871627
978  4.567247 2.389775 1.866258
979  3.813434 2.451984 1.870096
980  4.656749 2.600337 1.866014
981  3.645287 2.361263 1.873302
982  3.135193 2.548303 1.875394
983  5.340820 2.548551 1.861408
984  4.819511 2.500653 1.864953
985  3.880600 2.467557 1.870255
986  2.926652 2.542371 1.875978
987  3.081489 2.554773 1.876044
988  5.252563 2.458536 1.861773
989  4.333325 2.417528 1.867148
990  3.863229 2.568959 1.869776
991  5.260180 2.610899 1.861983
992  3.168345 2.545277 1.874800
993  4.597576 2.589320 1.866695
994  5.090457 2.470216 1.864154
995  5.003335 2.458658 1.864387
996  3.894586 2.525339 1.870236
997  4.202249 2.509422 1.869945
998  4.116801 2.450303 1.868720
999  4.044795 2.571683 1.870077
1000 3.240613 2.471092 1.874265

In [29]:
model_data <- function(n,betanote, betaone, betatwo, sims,me,sde,mx1,maxx2,minx2) {
  model.data <- data.frame(matrix(ncol = 3, nrow = sims))
  colnames(model.data) <- c("Beta0", "Beta1", "Beta2")
  
  for (i in 1:sims) {
    ertm <- rnorm(n, me, sde)
    X1 <- rt(n, mx1)
    X2 <- runif(n, minx2, maxx2)
    Y <- betanote + betaone * X1 + betatwo * X2 + ertm
    model.data[i, ] <- data.frame(t(lm(Y ~ X1 + X2)$coeff))
  }
  
  return(model.data)
}

result_data <- model_data(100,4,2.5,1.87,1000,0,1,4,200,130)
result_data

Beta0    Beta1    Beta2   
1    3.285398 2.496973 1.873201
2    5.064359 2.575743 1.863313
3    3.309016 2.479590 1.874793
4    5.258857 2.537772 1.862913
5    4.182195 2.552213 1.868522
6    3.208873 2.393784 1.874270
7    3.241665 2.604307 1.874624
8    4.372174 2.578110 1.867952
9    4.124676 2.509751 1.870083
10   5.248628 2.406036 1.861254
11   4.959290 2.405359 1.865755
12   3.887178 2.422818 1.869963
13   4.812871 2.510718 1.865694
14   3.537926 2.391788 1.872499
15   3.979292 2.636965 1.870125
16   3.919855 2.520403 1.870109
17   4.882949 2.481793 1.864924
18   5.131749 2.601335 1.862494
19   5.032710 2.533004 1.863812
20   5.082423 2.454543 1.862609
21   3.231602 2.516001 1.874309
22   4.140092 2.458941 1.869371
23   6.337993 2.507256 1.855565
24   2.393450 2.496924 1.880056
25   2.310873 2.450698 1.879941
26   3.488034 2.445515 1.872171
27   3.247711 2.417739 1.875206
28   5.197009 2.537707 1.863062
29   5.022248 2.587081 1.864828
30   3.426832 2.521793 1.873073
⋮    ⋮        ⋮        ⋮       
971  3.968028 2.563969 1.870317
972  4.072614 2.445756 1.868888
973  4.392806 2.427985 1.868072
974  4.977501 2.373071 1.864856
975  4.399217 2.454287 1.867300
976  2.458569 2.478416 1.879333
977  3.289325 2.377442 1.875480
978  3.838072 2.499344 1.872072
979  3.543385 2.512745 1.871277
980  3.672821 2.564996 1.872407
981  3.815570 2.475369 1.871045
982  3.604341 2.410465 1.872389
983  4.446578 2.574243 1.867380
984  4.110676 2.492651 1.868936
985  4.306451 2.597276 1.868170
986  3.973344 2.388699 1.870892
987  4.844832 2.592885 1.865468
988  3.502421 2.503142 1.872478
989  4.239972 2.451163 1.868914
990  4.216643 2.496319 1.869114
991  3.464296 2.488936 1.874158
992  4.765563 2.591740 1.866280
993  3.298688 2.465611 1.873946
994  3.795610 2.549427 1.871567
995  3.144824 2.525207 1.874805
996  4.179028 2.369153 1.869135
997  4.497395 2.401968 1.866359
998  3.409407 2.478107 1.873573
999  4.347836 2.529471 1.868377
1000 4.394360 2.545278 1.868429

In [30]:
func2<-function(x){
    res1<-max(x)
    res2<-min(x)
    res<-(x-res1)/(res1-res2)
    return(res)
}
d<-c(10,20,3,8,5,2)
func2(d)

[1] -0.5555556  0.0000000 -0.9444444 -0.6666667 -0.8333333 -1.0000000

In [31]:
Model <- lm(Y ~ x1 + x2)
summary(Model)


Call:
lm(formula = Y ~ x1 + x2)

Residuals:
     Min       1Q   Median       3Q      Max 
-101.081  -28.987    1.158   24.089   83.557 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 324.0092    36.5137   8.874 3.62e-14 ***
x1           -1.6143     2.6119  -0.618    0.538    
x2            0.1401     0.2174   0.645    0.521    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 39.73 on 97 degrees of freedom
Multiple R-squared:  0.007992,	Adjusted R-squared:  -0.01246 
F-statistic: 0.3907 on 2 and 97 DF,  p-value: 0.6776


In [33]:

n <- 500  
phi <- 0.35
theta <- 0.4
mu_z <- 0  
sigma_z <- sqrt(9) 
mu_x <- 3  
sigma_x <- sqrt(16)  


set.seed(123)  
Zt <- rnorm(n, mean = mu_z, sd = sigma_z)

X <- numeric(n)

for (t in 2:n) {
  Xt <- phi * X[t - 1] + Zt[t] + theta * Zt[t - 1]
  X[t] <- rnorm(1, mean = mu_x, sd = sigma_x) + Xt
}

Xt


[1] 2.738562

In [34]:
st<-c(21,20,18,19,17,19,20,19,20,15,19,18,14,14,15)
stest<-c()
stest[1]<-20
stest[2]<-21
for(t in 3:length(st)){
    et<-rnorm(1,0,1)
    stest[t]<-3 +(0.4*st[t-1])+(0.45*st[t-2])+et
}
stest

[1] 20.00000 21.00000 20.20081 18.20420 17.66004 18.33202 18.11782 17.00066
 [9] 20.64057 19.79973 20.41621 18.03520 18.30304 19.49739 17.73223

In [35]:
Age<-c(21,23,24,25,30,23)
Age 
Gender<-c("male","female","male","female","male","female")
Gender
Course<-c("BAS","BAS","BBS","BBS","BST","BST")
Course
students_data<-data.frame(Age,Gender,Course)
students_data
install.packages("dplyr")
library(dplyr)

[1] 21 23 24 25 30 23

[1] "male"   "female" "male"   "female" "male"   "female"

[1] "BAS" "BAS" "BBS" "BBS" "BST" "BST"

Age Gender Course
1 21  male   BAS   
2 23  female BAS   
3 24  male   BBS   
4 25  female BBS   
5 30  male   BST   
6 23  female BST

Installing package into 'C:/Users/ADMIN/AppData/Local/R/win-library/4.3'
(as 'lib' is unspecified)



package 'dplyr' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\ADMIN\AppData\Local\Temp\Rtmp6BLLiM\downloaded_packages


Warning message:
"package 'dplyr' was built under R version 4.3.2"

Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union




In [36]:
subset1<-select(students_data,Course,Gender)
subset1
subset2<-select(students_data,-Gender)
subset2
subset3<-select(students_data,starts_with("G"))
subset3

Course Gender
1 BAS    male  
2 BAS    female
3 BBS    male  
4 BBS    female
5 BST    male  
6 BST    female

Age Course
1 21  BAS   
2 23  BAS   
3 24  BBS   
4 25  BBS   
5 30  BST   
6 23  BST

Gender
1 male  
2 female
3 male  
4 female
5 male  
6 female

In [37]:
filter1<-filter(students_data,Age>25)
filter1
filter2<-filter(students_data,Age>=23&Age<=25)
filter2
filter3<-filter(students_data,Gender=="male")
filter3
filter4<-filter(students_data,Gender=="male"&Course=="BAS")
filter4

Age Gender Course
1 30  male   BST

Age Gender Course
1 23  female BAS   
2 24  male   BBS   
3 25  female BBS   
4 23  female BST

Age Gender Course
1 21  male   BAS   
2 24  male   BBS   
3 30  male   BST

Age Gender Course
1 21  male   BAS

In [38]:
Arrange1<-arrange(students_data,Age)
Arrange1

Age Gender Course
1 21  male   BAS   
2 23  female BAS   
3 23  female BST   
4 24  male   BBS   
5 25  female BBS   
6 30  male   BST

In [39]:
data<-rename(students_data,Degree=Course)
data

Age Gender Degree
1 21  male   BAS   
2 23  female BAS   
3 24  male   BBS   
4 25  female BBS   
5 30  male   BST   
6 23  female BST

In [40]:
dataset<-mutate(students_data,AgeDiff=Age-mean(Age))
dataset

Age Gender Course AgeDiff   
1 21  male   BAS    -3.3333333
2 23  female BAS    -1.3333333
3 24  male   BBS    -0.3333333
4 25  female BBS     0.6666667
5 30  male   BST     5.6666667
6 23  female BST    -1.3333333

In [41]:
data_bygender<-group_by(students_data,Gender)
data_bygender

Age Gender Course
1 21  male   BAS   
2 23  female BAS   
3 24  male   BBS   
4 25  female BBS   
5 30  male   BST   
6 23  female BST

In [42]:
data_bygender<-group_by(students_data,Gender)
data_bygender
summarize(data_bygender,meanAge=mean(Age),sdAge=sd(Age))

Age Gender Course
1 21  male   BAS   
2 23  female BAS   
3 24  male   BBS   
4 25  female BBS   
5 30  male   BST   
6 23  female BST

Gender meanAge  sdAge   
1 female 23.66667 1.154701
2 male   25.00000 4.582576

In [43]:
output<-mutate(students_data,AgeDiff=Age-mean(Age))%>% group_by(Gender)%>%summarize(meanAge=mean(Age),sdAge=sd(Age))
output

Gender meanAge  sdAge   
1 female 23.66667 1.154701
2 male   25.00000 4.582576

In [44]:
vec<-c(6,0,8,2,1,9,3,2,4)
vec
matvec<-matrix(vec,ncol=3,nrow=3)
matvec
apply(matvec,2,mean)
apply(matvec,1,mean)

[1] 6 0 8 2 1 9 3 2 4

[,1] [,2] [,3]
[1,] 6    2    3   
[2,] 0    1    2   
[3,] 8    9    4

[1] 4.666667 4.000000 3.000000

[1] 3.666667 1.000000 7.000000